name: frontend
description: "open fast lane frontend project"
# The following line prevents the package from being accidentally published to
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter_bloc: ^8.1.4
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  http: ^1.2.0
  flutter_web_auth: ^0.5.0
  go_router: ^13.0.1
  logger: ^2.0.2+1
  google_fonts: ^6.1.0
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.8.1
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  collection: ^1.18.0

dev_dependencies:
  mocktail: ^1.0.3
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

file_reporters:
  json: reports/test-results.json