name: frontend
description: "open fast lane frontend project"
# The following line prevents the package from being accidentally published to
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  get_it: ^7.6.6
  go_router: ^13.0.1
  logger: ^2.0.2+1
  google_fonts: ^6.1.0
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  mocktail: ^1.0.1
  bloc_test: ^9.1.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.0
  build_runner: ^2.4.5

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true

  assets:
   - assets/
