server:
  servlet:
    context-path: /api
  tomcat:
    threads:
      max: ${TOMCAT_MAX_THREADS:10}
    max-http-form-post-size: ${TOMCAT_MAX_HTTP_INPUT:11MB}
    max-swallow-size: ${TOMCAT_MAX_HTTP_INPUT:11MB}
    max-connections: ${TOMCAT_MAX_CONNECTIONS:5}

openfastlane:
  configDataDir: ${CONFIG_DATA_DIR:./config}
  insertDemoData: ${INSERT_DEMO_DATA:false}
  webBaseUrl: ${WEB_BASE_URL}
  mailing:
    senderFrom: ${MAIL_SENDER_FROM:noreply-test@openfastlane.at}
    senderName: ${MAIL_SENDER_NAME:noreply}
  tracking:
    piwikRootUrl: ${PIWIK_ROOT_URL:}
    piwikSiteId: ${PIWIK_SITE_ID:}
spring:
  data:
    redis:
      repositories:
        enabled: false
    mongodb:
      database: ${MONGO_DATABASE:openfastlane}
      uri: ${MONGO_URL:mongodb://ofl:password@localhost:27027}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_ISSUER_URI}
          jwk-set-uri: ${OAUTH_ISSUER_URI}/protocol/openid-connect/certs

  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:1025}
    username: ${SMTP_USERNAME:localhost}
    password: ${SMTP_PASSWORD:password}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls.enable: true
          starttls.required: true

  devtools:
    add-properties: false
  cache.type: simple
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_UPLOAD:10MB}
      max-request-size: ${MAX_FILE_UPLOAD:10MB}

  freemarker:
    checkTemplateLocation: true
    template-loader-path: classpath:/mail-templates/

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  info:
    git.enabled: true
    git.mode: full

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %boldGreen([%thread]) %cyan(%logger{15}.%M [%line]) - %msg%n%throwable'
  level:
    root: INFO
    at.sensatech.*: DEBUG
    web: INFO
    org.springframework.boot.autoconfigure: WARN
    org.springframework.cache: WARN
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG