= OpenFastlane API Documentation
Florian Hintermeier;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response


[[overview-http-status-codes]]
== HTTP status codes

RESTful notes tries to adhere as closely as possible to standard HTTP and REST conventions in its use of HTTP status codes.

|===
| Status code | Usage

| `200 OK`
|  The request completed successfully.
An update to an existing resource has been applied successfully

| `201 Created`
| A new resource has been created successfully.
The resource's URI is available from the response's
`Location` header

| `204 No Content`
| An update to an existing resource has been applied successfully

| `400 Bad Request`
| The request was malformed.
The response body will include an error providing further information.

| `401 Unauthorized`
| User is not logged in and Authorization is necessary

| `403 Forbidden`
| User is authenticated but Authorization is not given on this resource

| `404 Not Found`
| The requested resource did not exist, the URL describes nothing

| `405 Method not allowed`
| The requested path does not support this operation

| `409 Conflict`
| Another similar resource already exist, Creation is not possible

| `415 Unsupported Media Type`
| Only json is supported

| `451 Unavailable for legal reasons`
| A create or update request cannot be accepted due to use of reserved/restricted input

|===

[[overview-headers]]
== Headers

=== Requests

Every authenticated request needs at least the following header(s):

[source]
----
Content-Type: application/json
Accept: application/json
Authorization: Bearer $SECRET_ACCESS_TOKEN
----

[[overview-errors]]
== Errors

Whenever an error response (status code >= 400) is returned, the body will contain a JSON object that describes the problem.
The error object has the following structure:

For example, a request that attempts to register a user with an existing username
`400 Bad Request` response:

[[persons]]
== Persons

operation::persons-get[snippets='http-response,response-fields']

When request URL contains "?withEntitlements=true":

operation::persons-get-withEntitlements[snippets='http-response,response-fields']

When request URL contains "?withLastConsumptions=true":

operation::persons-get-withLastConsumptions[snippets='http-response,response-fields']

[[persons-create]]
=== POST /persons - Create new Person

operation::persons-create[snippets='curl-request,query-parameters,request-fields']

[[persons-update]]
=== PATCH /persons/:id - Update an existing Person

This is a PATCH request, which means that you only need to send the data you want to update.

operation::persons-update[snippets='curl-request,request-fields']

[[persons-list]]
=== GET /persons - Retrieve all Persons
operation::persons-list[snippets='curl-request']

[[persons-get]]
=== GET /persons/:id - Retrieve one Person
operation::persons-get[snippets='curl-request']

[[persons-similar]]
=== GET /persons/:id/similar - Retrieve one Person's similar persons

operation::persons-similar[snippets='curl-request']

[[persons-entitlements]]
=== GET /persons/:id/entitlements - Retrieve one Person's entitlements

operation::persons-entitlements[snippets='curl-request,http-response,response-fields']

[[persons-find]]
=== GET /persons/find - Find persons with similar names and/or address

operation::persons-findSimilarPersons[snippets='curl-request,query-parameters,http-response']

Returns *204 No Content* if no duplicates are found

[[persons-findSimilarPersons]]
=== GET /persons/findSimilarPersons - Find persons with similar names

operation::persons-findSimilarPersons[snippets='curl-request,query-parameters,http-response']

Returns *204 No Content* if no duplicates are found

operation::persons-findSimilarPersons-empty[snippets='http-response']

[[persons-findWithSimilarAddress]]
=== GET /persons/findWithSimilarAddress - Find persons with similar addresses

operation::persons-findWithSimilarAddress[snippets='curl-request,query-parameters,http-response']

Returns *204 No Content* if no duplicates are found

operation::persons-findWithSimilarAddress-empty[snippets='http-response']

[[entitlements]]
== Entitlements

operation::entitlements-get[snippets='http-response,response-fields']

[[entitlements-list]]
=== GET /entitlements - Retrieve all Entitlements

operation::entitlements-list[snippets='curl-request,http-response']

[[entitlements-create]]
=== POST /entitlements - Create new Entitlement for a Person

operation::entitlements-create[snippets='curl-request,request-fields,http-response']

[[entitlements-get]]
=== GET /entitlements/:id - Retrieve all Entitlements

operation::entitlements-get[snippets='curl-request,http-response']

[[entitlements-update]]
=== PUT /entitlements/:id - Update Entitlement

operation::entitlements-update[snippets='curl-request,request-fields,http-response']

[[entitlements-extend]]
=== POST /entitlements/:id - Create new Entitlement for a Person

operation::entitlements-extend[snippets='curl-request,http-response']

[[entitlements-update-qr]]
=== POST /entitlements/:id/update-qr - Update QR Code of Entitlement

operation::entitlements-update-qr[snippets='curl-request,http-response']

[[entitlements-view-qr]]
=== GET /entitlements/:id/qr - QR Code of Entitlement

operation::entitlements-view[snippets='curl-request,http-response']

[[consumptions]]
== Consumptions

operation::consumptions-find[snippets='http-response,response-fields']

[[consumptions-list]]
=== GET /consumptions/find? - Find Consumptions

operation::consumptions-find[snippets='curl-request,http-response,query-parameters']

[[entitlements-get-consumptions-list]]
=== GET /entitlements/:id/consumptions - List Consumptions of Entitlement

operation::entitlements-get-consumptions-list[snippets='http-response']

[[entitlements-can-consume]]
=== GET /entitlements/:id/can-consume - Check Consumption Possibility

operation::entitlements-can-consume[snippets='http-response,response-fields']

[[entitlements-perform-consumption]]
=== POST /entitlements/:id/consume - Perform Consumption

operation::entitlements-perform-consumption[snippets='http-response']

[[entitlement-causes]]
== Entitlements Cause

operation::entitlement-causes-get[snippets='http-response,response-fields']

[[entitlement-causes-list]]
=== GET /entitlement-causes - Retrieve all EntitlementCauses

operation::entitlement-causes-list[snippets='curl-request,http-response']

[[entitlement-causes-get]]
=== GET /entitlement-causes/:id - Retrieve all EntitlementCauses

operation::entitlement-causes-get[snippets='curl-request,http-response']

[[campaigns]]
== Campaigns

operation::campaigns-get[snippets='http-response,response-fields']

[[campaigns-list]]
=== GET /entitlements/ - List all Campaigns

operation::campaigns-list[snippets='curl-request,http-response']

[[campaigns-get]]
=== GET /entitlements/:id - Get a Campaign

operation::campaigns-get[snippets='curl-request,http-response']

[[campaign-causes-list]]
=== GET /entitlements/:id/causes - Get a Campaign's Causes

operation::campaign-causes-list[snippets='curl-request,http-response']

