name: Build and push image
on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'

jobs:
  build-image:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # change dir to backend
      - name: Change dir to backend
        run: cd backend

      - name: Build image
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: :server:bootBuildImage

      - name: Push image
        run: |
          docker image tag konekta-platform ghcr.io/sensatech/openfastlane:staging
          docker push ghcr.io/sensatech/openfastlane:staging
