name: Build and push images
on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
      - 'feature/*'

jobs:
  build-backend-image:
    name: Push backend image
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./backend

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.4

      - name: Build image
        run: ./gradlew :server:bootBuildImage

      - name: Push image
        run: |
          docker image tag openfastlane ghcr.io/sensatech/openfastlane-backend:staging
          docker push ghcr.io/sensatech/openfastlane-backend:staging

  build-frontend-image:
    name: Push frontend image
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: |
          docker build -t ghcr.io/sensatech/openfastlane-frontend:staging . -f frontend.Dockerfile
          docker image tag openfastlane-frontend ghcr.io/sensatech/openfastlane-frontend:staging
          docker push ghcr.io/sensatech/openfastlane-frontend:staging