name: Build and push image
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
      - 'develop'

defaults:
  run:
    shell: bash
    working-directory: ./backend

jobs:
  build-image:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.4

      - name: Build image
        run: ./gradlew :server:bootBuildImage

      - name: Push image
        run: |
          docker image tag openfastlane ghcr.io/sensatech/openfastlane:staging
          docker push ghcr.io/sensatech/openfastlane:staging
