name: Default PUSH-Pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - '**'

defaults:
  run:
    shell: bash
    working-directory: ./backend

env:
  CI_COMMIT_BRANCH: ${{ github.head_ref || github.ref_name }}
jobs:

  build-for-commit:
    name: Default PUSH-Pipeline
    runs-on: ubuntu-latest
    steps:

      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.4

      - name: Run Tests and Lint
        run: ./gradlew --stacktrace test asciidoctor jacocoTestReport jacocoTestCoverageVerification

      - name: Run Tests and Lint
        run: ./gradlew --stacktrace ktlintCheck

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'

      - name: Upload Test results
        uses: actions/upload-artifact@v4
        if: always() # always run even if the previous step fails
        with:
          name: test-results
          retention-days: 14
          path: |
            'backend/**/build/test-results/**/TEST-*.xml'
            'backend/**/build/reports/tests/**/TEST-*.xml'

      - name: Prepare REST docs
        run: |
          ./ci-tools/ci-docs-pages.sh

      - name: Upload REST docs
        uses: actions/upload-artifact@v4
        if: always() # always run even if the previous step fails
        with:
          name: rest-docs
          retention-days: 14
          path: 'backend/public'

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        continue-on-error: true
        if: always() # always run even if the previous step fails
        with:
          generate-branches-badge: true
          jacoco-csv-file: backend/**/build/reports/jacoco/test/jacocoTestReport.csv
          generate-coverage-badge: true
          coverage-badge-filename: jacoco.svg
          branches-badge-filename: branches.svg
          generate-summary: true
          summary-filename: coverage-summary.json

      - name: Update Jacoco Badge
        uses: test-room-7/action-update-file@v1
        with:
          branch: ${{ github.head_ref }}
          file-path: .github/badges/jacoco.svg
          commit-msg: Update Jacoco Badge
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60