name: Default PUSH-Pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
      
defaults:
  run:
    shell: bash
    working-directory: ./backend
      
env:
  CI_COMMIT_BRANCH: ${{ github.head_ref || github.ref_name }}
jobs:

  build-for-commit:
    name: Default PUSH-Pipeline
    runs-on: ubuntu-latest
    steps:

      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.4
       
      - name: Run Tests and Lint
        run: ./gradlew --stacktrace test asciidoctor jacocoTestReport
      
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'

      - name: Upload Test results
        uses: actions/upload-artifact@v4
        if: always() # always run even if the previous step fails
        with:
          name: test-results
          retention-days: 14
          path: |
            'backend/**/build/test-results/**/TEST-*.xml'
            'backend/**/build/reports/tests/**/TEST-*.xml'

      - name: Prepare REST docs
        run: |
          ./ci-tools/ci-docs-pages.sh

      - name: Upload REST docs
        uses: actions/upload-artifact@v4
        if: always() # always run even if the previous step fails
        with:
          name: rest-docs
          retention-days: 14
          path: 'backend/public'

