name: Release images to Container Registry
on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'   # Push events to every version tag /

jobs:
  release-backend-image:
    name: Release backend image
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./backend

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.4

      - name: Build image
        run: ./gradlew :server:bootBuildImage

      - name: Push release image
        run: |
          docker image tag openfastlane ghcr.io/sensatech/openfastlane/ofl-backend:latest
          docker image tag openfastlane ghcr.io/sensatech/openfastlane/ofl-backend:${{github.ref_name}}
          docker push ghcr.io/sensatech/openfastlane/ofl-backend:latest
          docker push ghcr.io/sensatech/openfastlane/ofl-backend:${{github.ref_name}}

  build-frontend-image:
    name: Release frontend image
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push release image
        run: |
          docker build -t ghcr.io/sensatech/openfastlane/ofl-frontend:latest . -f frontend.Dockerfile
          docker image tag ghcr.io/sensatech/openfastlane/ofl-frontend:latest ghcr.io/sensatech/openfastlane/ofl-frontend:${{github.ref_name}}
          docker push ghcr.io/sensatech/openfastlane/ofl-frontend:latest
          docker push ghcr.io/sensatech/openfastlane/ofl-frontend:${{github.ref_name}}
